version: '3'

services:
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    user: root
    ports:
      - "9083:9083"
      - "10000:10000"
    environment:
      - SERVICE_NAME=metastore
    volumes:
      - hive-data:/tmp
    command: >
      sh -c "
        mkdir -p /tmp/hive &&
        chmod -R 777 /tmp/hive &&
        /opt/hive/bin/schematool -dbType derby -initSchema &&
        /opt/hive/bin/hive --service metastore
      "

  spark-runner:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-runner
    depends_on:
      - hive-metastore
    volumes:
      - ./vehicle-etl.jar:/app/vehicle-etl.jar
      - ./init-data:/app/init-data
    command: echo "This is a placeholder. Real execution happens via run-etl-test.sh script." && sleep 30

volumes:
  hive-data:

networks:
  default:
    name: etl-network

